In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

In [6]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [7]:
print( "Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.52


In [8]:

print("Final Q-Table Values") 
print (Q)

Final Q-Table Values
[[2.49487766e-01 6.91576563e-03 1.06366974e-02 6.00083532e-03]
 [2.73923342e-04 1.84393678e-03 3.50076934e-04 2.79385247e-01]
 [3.14623098e-03 1.79389172e-03 3.83397894e-03 7.68952417e-02]
 [4.88274583e-04 1.95770414e-04 7.87153106e-04 4.24455898e-02]
 [1.81080290e-01 1.89856593e-04 3.53099862e-05 7.81096851e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.81362537e-02 2.75366433e-04 1.90786168e-04 7.31740240e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.41328352e-04 8.42602448e-04 4.56500781e-03 1.06830741e-01]
 [2.46721466e-03 2.29256959e-01 0.00000000e+00 1.03055934e-03]
 [6.42300615e-01 5.96698522e-04 1.70243963e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.92851669e-01 9.34971474e-05]
 [0.00000000e+00 0.00000000e+00 9.48237707e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.